package com.roze.enumeration;

public enum Source {

    COMMERCIAL_CONTRACT, EMAILING_CAMPAIGN, EMPLOYEE, FAX_CAMPAIGN,
    INTERNET, MAILING_CAMPAIGN, PARTNER, PHONE_CAMPAIGN, SHOP_CONTACT, SPONSORSHIP, WORD_OF_MOUTH;

}
